// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// enumerateDF
Rcpp::List enumerateDF(Rcpp::List tree_mats);
RcppExport SEXP _phydoser_enumerateDF(SEXP tree_matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tree_mats(tree_matsSEXP);
    rcpp_result_gen = Rcpp::wrap(enumerateDF(tree_mats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phydoser_enumerateDF", (DL_FUNC) &_phydoser_enumerateDF, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_phydoser(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
