# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

enumerateDF <- function(tree_mats) {
    .Call(`_phydoser_enumerateDF`, tree_mats)
}

